apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentication-service
  template:
    metadata:
      labels:
        app: authentication-service
    spec:
      containers: 
      - name: authentication-service
        image: "backentdev/authentication-service:1.0.0"
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
          - name: DSN
            value: "host=host.docker.internal port=5432 user=postgres password=postgres dbname=users sslmode=disable timezone=UTC connect_timeout=5"
        ports:
          - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: authentication-service
spec:
  selector:
    app: authentication-service
  ports:
    - protocol: TCP
      name: main-port
      port: 80
      targetPort: 80

# kubectl apply -f foldername/filename
# for example: kubectl apply -f k8s/authentication.yaml